/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author akshita
 */
public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form Flights
     */
    static String cid;
    static String sid;
    static int num;
    public String city= new String();
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    public Flights() {
        initComponents();
    }
     public Flights(String a, String b, int d) {
        
        initComponents();
        cid=a;
        sid=b;
        num=d;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ID1 = new javax.swing.JTextField();
        arr1 = new javax.swing.JTextField();
        dept1 = new javax.swing.JTextField();
        pp1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID2 = new javax.swing.JTextField();
        arr2 = new javax.swing.JTextField();
        dept2 = new javax.swing.JTextField();
        pp2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dt2 = new javax.swing.JTextField();
        dt1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        deptl1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        deptl2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 153, 51));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Place of choice :");

        jComboBox1.setBackground(new java.awt.Color(0, 153, 51));
        jComboBox1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bangalore", "Delhi", "Hyderabad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Flight Id:");

        jLabel3.setBackground(new java.awt.Color(0, 153, 51));
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Arrival Location:");

        jLabel4.setBackground(new java.awt.Color(0, 153, 51));
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Departure time:");

        jLabel5.setBackground(new java.awt.Color(0, 153, 51));
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Price per-head:");

        jLabel6.setBackground(new java.awt.Color(0, 153, 51));
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Arrival Location:");

        jLabel7.setBackground(new java.awt.Color(0, 153, 51));
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Departure time:");

        jLabel8.setBackground(new java.awt.Color(0, 153, 51));
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Price per-head:");

        ID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID2ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 153, 51));
        jLabel9.setForeground(new java.awt.Color(0, 153, 51));
        jLabel9.setText("Flight Id:");

        jLabel10.setBackground(new java.awt.Color(0, 153, 51));
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("Date");

        jLabel11.setBackground(new java.awt.Color(0, 153, 51));
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Date");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 153, 51));
        jLabel12.setForeground(new java.awt.Color(0, 153, 51));
        jLabel12.setText("Select to Book:");

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 153, 51));
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("Select to Book:");

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setForeground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deptl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptl1ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 153, 51));
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("Departure Location:");

        deptl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptl2ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 153, 51));
        jLabel15.setForeground(new java.awt.Color(0, 153, 51));
        jLabel15.setText("Departure Location:");

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setForeground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(153, 255, 153));
        jButton3.setText("Proceed To Book Hotels");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(36, 36, 36))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ID1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(arr1)
                                .addComponent(pp1)
                                .addComponent(dept1)
                                .addComponent(jCheckBox1)
                                .addComponent(deptl1))
                            .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deptl2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(arr2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)
                                .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ID2)
                                        .addComponent(dept2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox2))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deptl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dept1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deptl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dept2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel12)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        city=jComboBox1.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            
            String sq="Select f_id,arr_location,dept_location,time_dept,f_price from flights where s_id = ? and dept_location=?";
            PreparedStatement pstnt= conn.prepareStatement(sq);
            pstnt.setInt(1,Integer.parseInt(sid));
            pstnt.setString(2,city);
             rs= pstnt.executeQuery();
             if(rs.next())
             {
                 ID1.setText(rs.getString("f_id"));
                 arr1.setText(rs.getString("arr_location"));
                 deptl1.setText(rs.getString("dept_location"));
                 dept1.setText(rs.getString("time_dept"));
                 pp1.setText(rs.getString("f_price"));
             }
            String sql="Select f_id,arr_location,dept_location,time_dept,f_price from flights where s_id = ? and arr_location=?";
            PreparedStatement pstnt1= conn.prepareStatement(sql);
            pstnt1.setInt(1,Integer.parseInt(sid));
            pstnt1.setString(2,city);
             rs1= pstnt1.executeQuery();
             if(rs1.next())
             {
                 ID2.setText(rs1.getString("f_id"));
                 arr2.setText(rs1.getString("arr_location"));
                 deptl2.setText(rs1.getString("dept_location"));
                 dept2.setText(rs1.getString("time_dept"));
                 pp2.setText(rs1.getString("f_price"));
             }
             
            //JOptionPane.showMessageDialog(null,"inseted!!!");
            //conn.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(jCheckBox1.isSelected())
        {   try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            String sq3="Select c_id from f_booking where c_id =? and f_id =4040";
             
            PreparedStatement pstnt3= conn.prepareStatement(sq3);
             
            pstnt3.setInt(1,Integer.parseInt(cid));
            rs=pstnt3.executeQuery();
            if(rs.next())
            {
                String sq4 = "delete from f_booking where c_id = ? and f_id = 4040";
                PreparedStatement pstnt4 = conn.prepareStatement(sq4);
                pstnt4.setInt(1,Integer.parseInt(cid));
                pstnt4.executeUpdate();
            }
                
            String sq2="insert into f_booking values (?,?,?,?)";
            PreparedStatement pstnt2= conn.prepareStatement(sq2);
            pstnt2.setInt(1,Integer.parseInt(cid));
            pstnt2.setInt(2,Integer.parseInt(ID1.getText()));
            
           /* DateFormat format = new SimpleDateFormat("yyyy-mm-dd", Locale.ENGLISH);
            java.util.Date d1 = format.parse(dt1.getText());
            java.sql.Date d2 = new java.sql.Date(d1.getTime());*/
           
           DateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
           java.util.Date d1 =  formatter.parse(dt1.getText());
            
            pstnt2.setDate(3,new java.sql.Date(d1.getTime()));
            pstnt2.setInt(4,num*Integer.parseInt(pp1.getText()));
            //OptionPane.showMessageDialog(null,d2);
            //pstnt2.setDate(3, dt1.getText());
            pstnt2.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null,"Flight Booked");
       
            conn.close();
            }
            
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            }
        }
        
        if(!(jCheckBox1.isSelected()))
        {   
            try{
                
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            String sq5="Select c_id from f_booking where c_id =? and f_id in (select f_id from flights where s_id = ? and dept_location = ?)";
             
            PreparedStatement pstnt5= conn.prepareStatement(sq5);
             
            pstnt5.setInt(1,Integer.parseInt(cid));
            pstnt5.setInt(2,Integer.parseInt(sid));
            pstnt5.setString(3,deptl1.getText());
            rs=pstnt5.executeQuery();
            if(rs.next())
            {
                String sq6 = "delete from f_booking where c_id = ? and f_id in (select f_id from flights where s_id = ? and dept_location = ?)";
                PreparedStatement pstnt6 = conn.prepareStatement(sq6);
                pstnt6.setInt(1,Integer.parseInt(cid));
                pstnt6.setInt(2,Integer.parseInt(sid));
                pstnt6.setString(3,deptl1.getText());
                pstnt6.executeUpdate();
            }
            //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
                
           String sq7="insert into f_booking values (?,4040,null,0)";
             
            PreparedStatement pstnt2= conn.prepareStatement(sq7);
             
            pstnt2.setInt(1,Integer.parseInt(cid));
             pstnt2.executeUpdate();
            conn.close();
             JOptionPane.showMessageDialog(null,"Flight 1 not booked");
            
            
            }
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deptl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptl1ActionPerformed

    private void deptl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptl2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if(jCheckBox2.isSelected())
        {   try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            String sq3="Select c_id from f_booking where c_id =? and f_id =4041";
             
            PreparedStatement pstnt3= conn.prepareStatement(sq3);
             
            pstnt3.setInt(1,Integer.parseInt(cid));
            rs=pstnt3.executeQuery();
            if(rs.next())
            {
                String sq4 = "delete from f_booking where c_id = ? and f_id = 4041";
                PreparedStatement pstnt4 = conn.prepareStatement(sq4);
                pstnt4.setInt(1,Integer.parseInt(cid));
                pstnt4.executeUpdate();
            }
                
            String sq2="insert into f_booking values (?,?,?,?)";
            PreparedStatement pstnt2= conn.prepareStatement(sq2);
            pstnt2.setInt(1,Integer.parseInt(cid));
            pstnt2.setInt(2,Integer.parseInt(ID2.getText()));
            
           /* DateFormat format = new SimpleDateFormat("yyyy-mm-dd", Locale.ENGLISH);
            java.util.Date d1 = format.parse(dt1.getText());
            java.sql.Date d2 = new java.sql.Date(d1.getTime());*/
           
           DateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
           java.util.Date d1 =  formatter.parse(dt2.getText());
            
            pstnt2.setDate(3,new java.sql.Date(d1.getTime()));
            pstnt2.setInt(4,num*Integer.parseInt(pp2.getText()));
            //OptionPane.showMessageDialog(null,d2);
            //pstnt2.setDate(3, dt1.getText());
            pstnt2.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null,"Flight Booked");
       
            conn.close();
            }
            
            
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            }
        }
        
        if(!(jCheckBox2.isSelected()))
        {   
            try{
                
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            String sq5="Select c_id from f_booking where c_id =? and f_id in (select f_id from flights where s_id = ? and dept_location = ?)";
             
            PreparedStatement pstnt5= conn.prepareStatement(sq5);
             
            pstnt5.setInt(1,Integer.parseInt(cid));
            pstnt5.setInt(2,Integer.parseInt(sid));
            pstnt5.setString(3,deptl2.getText());
            rs=pstnt5.executeQuery();
            if(rs.next())
            {
                String sq6 = "delete from f_booking where c_id = ? and f_id in (select f_id from flights where s_id = ? and dept_location = ?)";
                PreparedStatement pstnt6 = conn.prepareStatement(sq6);
                pstnt6.setInt(1,Integer.parseInt(cid));
                pstnt6.setInt(2,Integer.parseInt(sid));
                pstnt6.setString(3,deptl2.getText());
                pstnt6.executeUpdate();
            }
            //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
                
           String sq7="insert into f_booking values (?,4041,null,0)";
             
            PreparedStatement pstnt2= conn.prepareStatement(sq7);
             
            pstnt2.setInt(1,Integer.parseInt(cid));
            pstnt2.executeUpdate();
            conn.close();
             JOptionPane.showMessageDialog(null,"Flight 2 not booked");
            
            
            }
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = "";
        String s2 = "";
            if(ID1.getText().equals(""))
            {
                s="4040";
            }
            else{
                s=ID1.getText();
            }
            
            if(ID2.getText().equals(""))
            {
                s2="4041";
            }
            else{
                s2=ID2.getText();
            }
            hotels h= new hotels(cid,sid,num,s,s2);
            h.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField ID2;
    private javax.swing.JTextField arr1;
    private javax.swing.JTextField arr2;
    private javax.swing.JTextField dept1;
    private javax.swing.JTextField dept2;
    private javax.swing.JTextField deptl1;
    private javax.swing.JTextField deptl2;
    private javax.swing.JTextField dt1;
    private javax.swing.JTextField dt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pp1;
    private javax.swing.JTextField pp2;
    // End of variables declaration//GEN-END:variables
}
