/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmt;

import static java.lang.Math.ceil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author akshita
 */
public class hotels extends javax.swing.JFrame {

    /**
     * Creates new form hotels
     */
    public hotels() {
        initComponents();
    }
    static String sid,cid,fid1,fid2;
    static int num;
    static int i=0;
    static  boolean a;
    ResultSet rs1 = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    hotels(String a,String b,int n,String f1, String f2) {
        initComponents();
        cid=a;
        sid=b;
        num=n;
        fid1=f1;
        fid2=f2;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotel1 = new javax.swing.JTextField();
        rating = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dt1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dt2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nextbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(null);
        jButton3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 255, 153));
        jButton3.setText(" HOTELS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        price.setText("   ");

        jComboBox1.setBackground(null);
        jComboBox1.setForeground(new java.awt.Color(0, 153, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(null);
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Hotel ID:");

        jLabel2.setBackground(null);
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Name:");

        jLabel3.setBackground(null);
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("Price per Room/Night:");

        dt1.setBackground(null);
        dt1.setForeground(new java.awt.Color(0, 153, 102));
        dt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(null);
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("Date Of Checkin:");

        dt2.setBackground(null);
        dt2.setForeground(new java.awt.Color(0, 153, 102));
        dt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(null);
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("Date Of Checkout:");

        jComboBox2.setBackground(null);
        jComboBox2.setForeground(new java.awt.Color(0, 153, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "3000", "5000", "7000" }));

        jLabel6.setBackground(null);
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("Rating:");

        nextbutton.setBackground(null);
        nextbutton.setForeground(new java.awt.Color(0, 153, 102));
        nextbutton.setText("Next");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });

        jButton1.setBackground(null);
        jButton1.setForeground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Confirm Stay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(nextbutton)
                        .addGap(134, 392, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(311, 311, 311))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(11, 11, 11)))
                                .addGap(33, 33, 33)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hotel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(nextbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotel1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try{
            
            
         int j =0;
         int t=200;
        
         
         
         
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            
            String sq="select h_id,h_name,h_price,h_rating from hotels where s_id = ? and h_id in (select h_id from hotels where h_price <= ?) and h_id in (select h_id from hotels where h_rating >= ?)";
            PreparedStatement pstnt= conn.prepareStatement(sq);
            pstnt.setInt(1,Integer.parseInt(sid));
            pstnt.setInt(2,Integer.parseInt(jComboBox2.getSelectedItem().toString()));
            pstnt.setFloat(3,Float.parseFloat(jComboBox1.getSelectedItem().toString()));
            rs= pstnt.executeQuery();
            
         String s1[] = new String[50];
         String s2[] = new String[50];
         String s3[] = new String[50];
         String s4[] = new String[50];
            
            //int k=0;
            rs.last();
            t=rs.getRow();
            if(t==0)
            {
                JOptionPane.showMessageDialog(null, "No Hotel with Such Conditions. Please Change Conditions");
            }
            rs.beforeFirst();
            
            
            while(rs.next())
            {
                s1[j] = rs.getString("h_id");
                s2[j]=rs.getString("h_name");
                s3[j]=rs.getString("h_price");
                s4[j]=rs.getString("h_rating");
                j=j+1;
            }
            
            
         
          
            
            rs.beforeFirst();
            
            if(rs.next()){
                a=true;
            hotel1.setText(s1[i]);
            name1.setText(s2[i]);
            price.setText(s3[i]);
            rating.setText(s4[i]);
            if(t!=1)
            {i++;  
            
            }
            
            
            if(i==t)
                i=0;
            
           
     }
            else{
                a=false;
                hotel1.setText("");
            name1.setText("");
            price.setText("");
            rating.setText("");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt1ActionPerformed

    private void dt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(a){
        try{
                
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            String sq5="Select count(c_id) from details where c_id =? and age <=? ";
             
            PreparedStatement pstnt5= conn.prepareStatement(sq5);
             
            pstnt5.setInt(1,Integer.parseInt(cid));
            pstnt5.setInt(2,12);
            rs1=pstnt5.executeQuery();
            rs1.last();
            int j=rs1.getRow();
            
            
            //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/wildlife","root","");
            int m;
            if(j==0)
            {
                m=num;
            }
            else{
            int t = rs1.getInt(1);
            
             JOptionPane.showMessageDialog(null,t);
             m = num-t;
            if(m%2!=0)
            {
                m=m/2+1;
            }
            else{
                m=m/2;
            }
          String sq7="insert into h_booking values (?,?,?,?,?,?)";
             
           PreparedStatement pstnt2= conn.prepareStatement(sq7);
            
           pstnt2.setInt(1,Integer.parseInt(cid));
            pstnt2.setInt(2,Integer.parseInt(hotel1.getText()));
           pstnt2.setInt(3, m);
            
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date d1 =  formatter.parse(dt1.getText());
            pstnt2.setDate(4,new java.sql.Date(d1.getTime()));
            
            DateFormat formattr = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date d2 =  formattr.parse(dt2.getText());
            pstnt2.setDate(5,new java.sql.Date(d2.getTime()));
            pstnt2.setInt(6,0);
            pstnt2.executeUpdate();
            
            //conn.close()
            String sq8="Select d_checkout - d_checkin from h_booking where c_id = ?";
             
           PreparedStatement pstnt3= conn.prepareStatement(sq8);
           pstnt3.setInt(1,Integer.parseInt(cid));
           //pstnt3.setInt(2,Integer.parseInt(hotel1.getText()));
           rs2 = pstnt3.executeQuery();
           int d=0;
           if(rs2.next())
           {
            d = rs2.getInt(1);
           }
           int f = d*m*(Integer.parseInt(price.getText()));
           String sq9 = "Update h_booking set stay_price = ? where c_id = ? and h_id = ?";
           PreparedStatement pstnt4= conn.prepareStatement(sq9);
           pstnt4.setInt(1,f);
           pstnt4.setInt(2,Integer.parseInt(cid));
           pstnt4.setInt(3,Integer.parseInt(hotel1.getText()));
           pstnt4.executeUpdate();
           
           Services se1 = new Services(cid,sid,num,fid1,fid2,hotel1.getText());
           se1.setVisible(true);
           dispose();
           
           
            
            }
        }
            catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
            }
        
        
        }
        else{
             JOptionPane.showMessageDialog(null,"Select Hotel please");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dt1;
    private javax.swing.JTextField dt2;
    private javax.swing.JTextField hotel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name1;
    private javax.swing.JButton nextbutton;
    private javax.swing.JTextField price;
    private javax.swing.JTextField rating;
    // End of variables declaration//GEN-END:variables
}
